/*enum {
	IMAGE_NORMAL = 0,
	IMAGE_H_MIRROR,
	IMAGE_V_MIRROR,
	IMAGE_HV_MIRROR
};
*/

#ifndef IMAGE_CUST_MIRROR
#define IMAGE_CUST_MIRROR IMAGE_HV_MIRROR
#define IMAGE_CUST_COLOR_ORDER	SENSOR_OUTPUT_FORMAT_RAW_R
#endif